// =============================================================================
// ECCLESIA Electron Main Process
// =============================================================================
// Starts the Express backend, creates the BrowserWindow, manages system tray,
// and handles "close to tray" behavior for a native desktop experience.
// =============================================================================

import { app, BrowserWindow, Tray, Menu, nativeImage, ipcMain, dialog, shell } from 'electron';
import { spawn } from 'node:child_process';
import crypto from 'node:crypto';
import net from 'node:net';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Dev vs production:
//  - Packaged app  -> production
//  - ELECTRON_MODE=production  -> force production (useful when running unpackaged)
//  - ELECTRON_MODE=development -> force development
//  - Otherwise (plain `electron .`) -> development
const isDev =
  process.env.ELECTRON_MODE === 'development' ||
  (!app.isPackaged && process.env.ELECTRON_MODE !== 'production');

// The app ships a strict Content-Security-Policy (vite dev header + index.html
// <meta> + helmet() in production), so the renderer is genuinely locked down.
// Electron still prints its dev-mode "Insecure Content-Security-Policy" warning
// on some setups even with a valid CSP (known issue: electron/electron#31029),
// so suppress that dev-only noise here. Packaged builds never show it.
if (isDev) {
  process.env.ELECTRON_DISABLE_SECURITY_WARNINGS = 'true';

  // The renderer's Chromium can resolve `localhost` to ::1 while the vite dev
  // server listens on 0.0.0.0 (IPv4 only), so the HMR websocket gets
  // ERR_CONNECTION_REFUSED. Pin localhost to 127.0.0.1 so the renderer's HTTP
  // and WebSocket connections always reach the same listener.
  app.commandLine.appendSwitch('host-resolver-rules', 'MAP localhost 127.0.0.1');
}

// In production (packaged), resources are at process.resourcesPath
// extraResources from electron-builder places backend at process.resourcesPath/backend
const ROOT_DIR = isDev ? path.resolve(__dirname, '..') : process.resourcesPath;
const BACKEND_DIR = path.join(ROOT_DIR, 'backend');
const USER_DATA_DIR = app.getPath('userData');
const DB_PATH = path.join(USER_DATA_DIR, 'ecclesia.db');
const BACKEND_PORT = process.env.PORT || '5000';
const LOAD_URL = isDev ? 'http://localhost:3000' : `http://127.0.0.1:${BACKEND_PORT}`;

let backendProcess = null;
let mainWindow = null;
let tray = null;
let isQuitting = false;

// Ensure userData directory exists
if (!fs.existsSync(USER_DATA_DIR)) {
  fs.mkdirSync(USER_DATA_DIR, { recursive: true });
}

// First run: the packaged app ships an empty-schema template database
// (resources/backend/template.db — generated by `npm run prepare:template`).
// Copy it into userData so the backend has tables + singleton rows to work
// with; the parish administrator is then created interactively by the
// first-run setup screen (POST /api/auth/bootstrap). Never overwrite an
// existing database.
if (!fs.existsSync(DB_PATH)) {
  const templateDb = path.join(ROOT_DIR, 'backend', 'template.db');
  if (fs.existsSync(templateDb)) {
    try {
      fs.copyFileSync(templateDb, DB_PATH);
      console.log('[Electron] Initialized fresh database from template.');
    } catch (err) {
      console.error('[Electron] Failed to copy template database:', err);
    }
  } else {
    console.warn('[Electron] No template database found at', templateDb);
  }
}

// Set DATABASE_URL for the backend process BEFORE spawning it
process.env.DATABASE_URL = `file:${DB_PATH}`;

// =============================================================================
// Backend Process Management
// =============================================================================

// Quick TCP check to see if the backend is already listening on BACKEND_PORT.
// Prevents double-starting the backend (e.g. when Electron is launched while a
// dev server is already running on port 5000).
function isBackendRunning(timeoutMs = 1500) {
  return new Promise((resolve) => {
    const socket = net.connect(Number(BACKEND_PORT), '127.0.0.1');
    const done = (ok) => {
      socket.destroy();
      resolve(ok);
    };
    socket.setTimeout(timeoutMs);
    socket.once('connect', () => done(true));
    socket.once('timeout', () => done(false));
    socket.once('error', () => done(false));
  });
}

function startBackend() {
  return new Promise(async (resolve, reject) => {
    // If a backend is already running on the target port, reuse it.
    if (await isBackendRunning()) {
      console.log(`[Electron] Backend already running on :${BACKEND_PORT} — reusing it.`);
      return resolve();
    }

    let command;
    let args;    if (isDev) {
      // Resolve the local tsx shim (Windows needs the .cmd wrapper).
      const tsxBin = path.join(
        BACKEND_DIR,
        'node_modules',
        '.bin',
        process.platform === 'win32' ? 'tsx.cmd' : 'tsx',
      );
      command = tsxBin;
      args = ['watch', 'src/index.ts'];
    } else {
      command = process.platform === 'win32' ? 'node.exe' : 'node';
      args = ['dist/index.js'];
    }
    const env = { ...process.env, DATABASE_URL: `file:${DB_PATH}`, PORT: BACKEND_PORT };
    if (!isDev) {
      // Run the packaged backend in production mode with a STABLE JWT secret
      // persisted next to the database in userData (survives restarts, travels
      // with the data folder when backed up). Without this the backend would
      // run in dev mode with a randomly regenerated secret.
      env.NODE_ENV = 'production';
      // Stable JWT secret persisted next to the database in userData (survives
      // restarts, travels with the data folder when backed up). Without this
      // the backend would run in dev mode with a randomly regenerated secret.
      const secretPath = path.join(USER_DATA_DIR, 'jwt-secret');
      if (!fs.existsSync(secretPath)) {
        fs.writeFileSync(secretPath, crypto.randomBytes(48).toString('hex'), { encoding: 'utf8', flag: 'wx' });
      }
      env.JWT_SECRET = fs.readFileSync(secretPath, 'utf8').trim();
      // Automatic DB backups belong next to the database (userData), not in the
      // install directory where they could be lost on uninstall.
      env.BACKUP_DIR = path.join(USER_DATA_DIR, 'backups');
    }

    console.log('[Electron] Starting backend...', { command, args, cwd: BACKEND_DIR, dbPath: DB_PATH });

    backendProcess = spawn(command, args, {
      cwd: BACKEND_DIR,
      env,
      stdio: ['ignore', 'pipe', 'pipe'],
      windowsHide: true,
    });

    backendProcess.stdout?.on('data', (data) => {
      const output = data.toString().trim();
      console.log('[Backend]', output);
      if (output.includes('Ecclesia Server running') || output.includes(`running on http://localhost:${BACKEND_PORT}`)) {
        resolve();
      }
    });

    backendProcess.stderr?.on('data', (data) => {
      console.error('[Backend ERROR]', data.toString().trim());
    });

    backendProcess.on('error', (err) => {
      console.error('[Electron] Failed to start backend:', err);
      reject(err);
    });

    backendProcess.on('exit', (code, signal) => {
      if (!isQuitting) {
        console.log('[Electron] Backend exited unexpectedly:', { code, signal });
        // Could implement auto-restart here if needed
      }
      backendProcess = null;
    });

    // Timeout fallback
    setTimeout(() => resolve(), 8000);
  });
}

function stopBackend() {
  if (backendProcess) {
    console.log('[Electron] Stopping backend...');
    backendProcess.kill('SIGTERM');
    backendProcess = null;
  }
}

// =============================================================================
// Window Creation
// =============================================================================

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1400,
    height: 900,
    minWidth: 1100,
    minHeight: 700,
    title: 'ECCLESIA Church Management System',
    icon: path.join(__dirname, 'assets', 'icon-256.png'),
    // Frameless window — the app renders its own slim OS-style title bar
    // (brand, drag region + window controls) in TitleBar.tsx, above the nav.
    // The native title bar and application menu (File/Edit/View/...) are
    // removed; window controls are driven via the preload bridge.
    frame: false,
    backgroundColor: '#f8fafc', // slate-50, avoids white flash while loading
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
    show: false, // Show after ready to avoid flicker
  });

  const loadUrl = LOAD_URL;

  // Surface preload failures loudly (e.g. sandbox/ESM mismatches) instead of
  // silently losing the window.electronAPI bridge.
  mainWindow.webContents.on('preload-error', (_event, preloadPath, error) => {
    console.error('[Electron] Preload failed to load:', preloadPath, error);
  });

  // Load the app URL with retries: on a fresh install the packaged backend can
  // take a couple of seconds to finish cold-starting, so the first load attempt
  // may race it (ERR_CONNECTION_REFUSED). Retry until it connects (bounded), in
  // both dev and packaged modes.
  const loadAppUrl = (attempt = 0) => {
    mainWindow?.loadURL(loadUrl).catch((err) => {
      console.error('[Electron] Failed to load URL (attempt ' + (attempt + 1) + '):', err);
      if (attempt < 10) {
        setTimeout(() => loadAppUrl(attempt + 1), 1000);
      }
    });
  };
  loadAppUrl();

  mainWindow.once('ready-to-show', () => {
    mainWindow?.show();
    if (isDev) {
      mainWindow?.webContents.openDevTools({ mode: 'detach' });
    }
  });

  // Handle window close - minimize to tray instead of quitting
  mainWindow.on('close', (event) => {
    if (!isQuitting) {
      event.preventDefault();
      mainWindow?.hide();
    }
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });

  // Keep the renderer's custom title bar in sync with the maximize state
  // (so the maximize/restore button shows the right icon).
  const emitMaximized = () => {
    mainWindow?.webContents.send('window:maximized-changed', mainWindow?.isMaximized());
  };
  mainWindow.on('maximize', emitMaximized);
  mainWindow.on('unmaximize', emitMaximized);

  // Handle external links
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    try {
      const parsed = new URL(url);
      if (parsed.protocol === 'http:' || parsed.protocol === 'https:') {
        shell.openExternal(url);
      }
    } catch {
      // Ignore invalid URLs
    }
    return { action: 'deny' };
  });
}

// =============================================================================
// System Tray
// =============================================================================

function createTray() {
  // Brand-consistent 32px tray glyph (dark rounded square + white cross),
  // resized for the tray (16px on Windows).
  const iconPath = path.join(__dirname, 'assets', 'icon-32.png');
  let trayIcon = nativeImage.createFromPath(iconPath);
  
  // Resize for tray (16x16 on Windows, 22x22 on macOS)
  trayIcon = trayIcon.resize({ width: 16, height: 16 });

  tray = new Tray(trayIcon);
  tray.setToolTip('ECCLESIA Church Management System');

  const contextMenu = Menu.buildFromTemplate([
    {
      label: 'Open ECCLESIA',
      click: () => {
        mainWindow?.show();
        mainWindow?.focus();
      },
    },
    { type: 'separator' },
    {
      label: 'Quit',
      click: () => {
        isQuitting = true;
        app.quit();
      },
    },
  ]);

  tray.setContextMenu(contextMenu);

  // Double-click tray icon to show window
  tray.on('double-click', () => {
    mainWindow?.show();
    mainWindow?.focus();
  });
}

// =============================================================================
// App Lifecycle
// =============================================================================

app.whenReady().then(async () => {
  try {
    await startBackend();
    createWindow();
    createTray();

    // macOS: re-create window when dock icon is clicked
    app.on('activate', () => {
      if (BrowserWindow.getAllWindows().length === 0) createWindow();
    });
  } catch (err) {
    console.error('[Electron] Failed to start app:', err);
    dialog.showErrorBox('ECCLESIA Startup Error', `Failed to start the application:\n${err}`);
    app.quit();
  }
});

app.on('window-all-closed', () => {
  // On macOS, keep app running in tray; on Windows/Linux, quit only if explicitly quitting
  if (process.platform !== 'darwin' && !isQuitting) {
    // Keep running in tray
  } else if (isQuitting) {
    stopBackend();
    app.quit();
  }
});

app.on('before-quit', () => {
  isQuitting = true;
  stopBackend();
});

// =============================================================================
// IPC Handlers (secure communication from renderer)
// =============================================================================

ipcMain.handle('app:getVersion', () => app.getVersion());
ipcMain.handle('app:getPath', (_event, name) => app.getPath(name));

// =============================================================================
// Custom Title Bar — Window Controls
// =============================================================================
// The frameless window renders its own minimize/maximize/close buttons inside
// the app header (Header.tsx). These handlers drive the native window.

ipcMain.on('window:minimize', () => mainWindow?.minimize());
ipcMain.on('window:toggleMaximize', () => {
  if (!mainWindow) return;
  if (mainWindow.isMaximized()) mainWindow.unmaximize();
  else mainWindow.maximize();
});
ipcMain.on('window:close', () => mainWindow?.close()); // close-to-tray (hide)
ipcMain.handle('window:isMaximized', () => mainWindow?.isMaximized() ?? false);

// =============================================================================
// Hide the default application menu (File / Edit / View / Window / Help).
// Menu items are reachable via keyboard shortcuts (Ctrl+Shift+I for DevTools);
// the unified title bar intentionally shows no menu.
// =============================================================================

app.whenReady().then(() => {
  Menu.setApplicationMenu(null);
});

// =============================================================================
// Security: Prevent new window creation from renderer
// =============================================================================

app.on('web-contents-created', (_event, contents) => {
  contents.setWindowOpenHandler(() => ({ action: 'deny' }));
  contents.on('will-navigate', (navEvent, url) => {
    const allowedOrigins = [new URL(LOAD_URL).origin];
    if (!allowedOrigins.some((origin) => url.startsWith(origin))) {
      navEvent.preventDefault();
    }
  });
});